spring:
  datasource:
    url: jdbc:postgresql://db.sqxownsstsoebicbktru.supabase.co:5432/postgres
    username: postgres
    password: a2972638139
    driver-class-name: org.postgresql.Driver

jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mvc:
    cors:
      allowed-origins: ""



