spring:
  datasource:
    url: jdbc:postgresql://db.sqxownsstsoebicbktru.supabase.co:5432/postgres
    username: postgres
    password: a2972638139
    driver-class-name: org.postgresql.Driver

jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mvc:
    cors:
      allowed-origins: "http://localhost:5173,http://localhost:5174,https://lff553.github.io"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600


